# Conda recipe for Magni

package:
  name: magni
  version: '1.7.0'

source:
  fn: magni-1.7.0.tar.gz
  url: https://pypi.python.org/packages/d8/b5/88f964cd56097ca8b364b02b2d5664870b68b693eb5a658030b3fa87e050/magni-1.7.0.tar.gz
  md5: 6b2016652cbd0d5dd223f168b67a1a7e

  patches:
    - setup_py_conda.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools >=11.3
  run:
    - python
    - numpy >=1.8
    - pytables >=3.1
    - scipy >=0.14
    - matplotlib >=1.3
    - setuptools >=11.3

test:
  requires:
    - nose

  imports:
    - magni

about:
  home: https://github.com/SIP-AAU/Magni
  license: BSD 2-Clause
  summary: A Python Package for Compressive Sampling Reconstruction of Atomic Force Microscopy Images
  
